### PR TITLE
Update to README.md and Dockerfile

### PR DESCRIPTION
**Pull request by rwcitek**
Have a look at the additional text around the docker build.
Also, created three examples.  Have a look to see if they work for you.

### CODE REVIEW

**Comment by edhowland** [comment]
Just a comment to see how interactive participation goes. Comment back at me. I checked out the README.md file, I think you also made a ./docker/Dockerfile in the commit. I haven't check that out yet.
After 1-2 of these back and forths, I will merge, probably with no reccomended changes.
Again, just for practice.
- Ed

**Comment by rwcitek** [comment]
I got this comment via email, so I’m responding by replying in email.

As for the Dockerfile, I have not created it in the repo. I’ve only
referenced it in the README. I’ll create it later and issue another PR.

Until then, what are your thoughts on the examples for using the docker
commands?

Regards,
- Robert

**Comment by rwcitek** [comment]
I created a nascent Dockerfile and updated the README.md file.  I see them listed in this conversation thread, which makes it look like they've been added to this PR.

**Comment by rwcitek** [comment]
BTW, I was reading about Dockerfile Best Practices and there's a section on using Here-Documents.

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#pipe-dockerfile-through-stdin

**Comment by edhowland** [comment]
Ok. I read that link and I also think I referenced in another email. As far as I can determine, use stdin/here documents if you do not want use a build context. A build context is here you have created a seperate folder with (at least) a Dockerfile in it, and possibly application context recursively under that folder. (The "." that appears in docker build -t <tag> . examples)
This build context is sent to the docker daemon and looks like a performance bottleneck, especially if you have nothing in the dir other than the Dockerfile. Or, if you are somehow retrieving the contents of a Dockerfile from some remote location.

Maybe a good question for tomorrow?

Again, my only object is to make things clear for new Python beginners.
My thought was to use Dockerfiles in a code fence, but if we can link to a proper Dockerfile/docker folder, then that is just as well.

**Comment by rwcitek** [comment]
Totally agree with keeping it simple for the end user.  I think it’s nice that we have both methods: a Here-Doc and a Dockerfile.  A Here-Doc makes sense in the context of the README.md file as it is a command that can be cut-n-paste into the terminal and it will run.  The Dockerfile should not be in the README.md, IMHO, as it is not a command that you can cut-paste. Rather, you first have to put it in a file and then run `docker build ...`.  Plus, by having it as its own file, you follow the convention of so many other projects. Also, there's one more bonus to having it as its own file: with this comment, we cover the third method to build a Docker image: using a URL.

$ docker build -t my_python:3.10 https://raw.githubusercontent.com/rwcitek/PythonResources/main/docker/Dockerfile

**Comment by edhowland** [comment]
after review, merging without changes.

**Pull request merged**
